from django.db import models

# Create your models here.
Order_State = [('OPEN','OPEN'),('CLOSED','CLOSED')]
class Order_detail(models.Model):
    Table_number = models.IntegerField(null=False)
    Number_Of_Person = models.IntegerField(null=False)
    Discount = models.IntegerField(default=0)
    item0 = models.CharField(max_length=300)
    item_rate0 = models.IntegerField(null = False)
    item_qty0 = models.IntegerField(default=0)
    item_total0 = models.IntegerField(null = False)
    item1 = models.CharField(max_length=300)
    item_rate1 = models.IntegerField(null = False)
    item_qty1 = models.IntegerField(default=0)
    item_total1 = models.IntegerField(null = False)
    item2 = models.CharField(max_length=300)
    item_rate2 = models.IntegerField(null = False)
    item_qty2 = models.IntegerField(default=0)
    item_total2 = models.IntegerField(null = False)
    item3 = models.CharField(max_length=300)
    item_rate3 = models.IntegerField(null = False)
    item_qty3 = models.IntegerField(default=0)
    item_total3 = models.IntegerField(null = False)
    item4 = models.CharField(max_length=300)
    item_rate4 = models.IntegerField(null = False)
    item_qty4 = models.IntegerField(default=0)
    item_total4 = models.IntegerField(null = False)
    item5 = models.CharField(max_length=300)
    item_rate5 = models.IntegerField(null = False)
    item_qty5 = models.IntegerField(default=0)
    item_total5 = models.IntegerField(null = False)
    item6 = models.CharField(max_length=300)
    item_rate6 = models.IntegerField(null = False)
    item_qty6 = models.IntegerField(default=0)
    item_total6 = models.IntegerField(null = False)
    item7 = models.CharField(max_length=300)
    item_rate7 = models.IntegerField(null = False)
    item_qty7 = models.IntegerField(default=0)
    item_total7 = models.IntegerField(null = False)
    item8 = models.CharField(max_length=300)
    item_rate8 = models.IntegerField(null = False)
    item_qty8 = models.IntegerField(default=0)
    item_total8 = models.IntegerField(null = False)
    item8 = models.CharField(max_length=300)
    item_rate8 = models.IntegerField(null = False)
    item_qty8 = models.IntegerField(default=0)
    item_total8 = models.IntegerField(null = False)
    item9 = models.CharField(max_length=300)
    item_rate9 = models.IntegerField(null = False)
    item_qty9 = models.IntegerField(default=0)
    item_total9 = models.IntegerField(null = False)
    total = models.IntegerField()
    Order_date = models.DateTimeField()
    Order_Status = models.CharField(max_length=30,choices=Order_State,default='OPEN')
    
    
