# Generated by Django 4.2 on 2023-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_staff_detail1_delete_staff_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_No', models.IntegerField()),
                ('Emp_Name', models.CharField(max_length=200)),
                ('Amount_Paid', models.IntegerField()),
                ('Amount_Paid_Date', models.DateField()),
            ],
        ),
    ]
