# Generated by Django 4.2 on 2023-04-22 13:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_salary_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_date', models.DateField()),
                ('description', ckeditor.fields.RichTextField()),
                ('Daily_Total', models.IntegerField()),
            ],
        ),
    ]
