# Generated by Django 4.2 on 2023-04-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_Name', models.CharField(max_length=150)),
                ('Shop_address', models.CharField(max_length=150)),
                ('Number', models.CharField(max_length=13)),
            ],
        ),
    ]
