# Generated by Django 4.2 on 2023-04-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_rate', models.IntegerField()),
            ],
        ),
    ]
