# Generated by Django 4.2 on 2023-04-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='Discount',
            field=models.IntegerField(default=0),
        ),
    ]
