# Generated by Django 4.2 on 2023-04-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_detail_item_rate0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='Table_number',
            field=models.CharField(max_length=10),
        ),
    ]
