# Generated by Django 4.2 on 2023-04-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_detail_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='Table_number',
            field=models.IntegerField(),
        ),
    ]
